from telacore.exceptions import DataBaseException

def test():
    raise DataBaseException('dsdsdds')


test()